// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-VzJ4xxsvjaafkfoeFw9rSpsKsN_xcuw',
    appId: '1:893081783754:web:c8ec1612dd49a3946f1333',
    messagingSenderId: '893081783754',
    projectId: 'success-motors-98133',
    authDomain: 'success-motors-98133.firebaseapp.com',
    databaseURL: 'https://success-motors-98133-default-rtdb.firebaseio.com',
    storageBucket: 'success-motors-98133.firebasestorage.app',
    measurementId: 'G-8DGTE33GGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnIe396RD7XmDPrufEVYkGsa1tNW6HXNE',
    appId: '1:893081783754:android:ce19c8f5318c48406f1333',
    messagingSenderId: '893081783754',
    projectId: 'success-motors-98133',
    databaseURL: 'https://success-motors-98133-default-rtdb.firebaseio.com',
    storageBucket: 'success-motors-98133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXkNTkxWTlf8yi72bpVBlZT7hRiRo1In8',
    appId: '1:893081783754:ios:011f9020941838dd6f1333',
    messagingSenderId: '893081783754',
    projectId: 'success-motors-98133',
    databaseURL: 'https://success-motors-98133-default-rtdb.firebaseio.com',
    storageBucket: 'success-motors-98133.firebasestorage.app',
    iosClientId: '893081783754-79uq8guosf25fppcr60gtf75mqfovs9j.apps.googleusercontent.com',
    iosBundleId: 'com.swift.successMotors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXkNTkxWTlf8yi72bpVBlZT7hRiRo1In8',
    appId: '1:893081783754:ios:011f9020941838dd6f1333',
    messagingSenderId: '893081783754',
    projectId: 'success-motors-98133',
    databaseURL: 'https://success-motors-98133-default-rtdb.firebaseio.com',
    storageBucket: 'success-motors-98133.firebasestorage.app',
    iosClientId: '893081783754-79uq8guosf25fppcr60gtf75mqfovs9j.apps.googleusercontent.com',
    iosBundleId: 'com.swift.successMotors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-VzJ4xxsvjaafkfoeFw9rSpsKsN_xcuw',
    appId: '1:893081783754:web:c1b508b1130329756f1333',
    messagingSenderId: '893081783754',
    projectId: 'success-motors-98133',
    authDomain: 'success-motors-98133.firebaseapp.com',
    databaseURL: 'https://success-motors-98133-default-rtdb.firebaseio.com',
    storageBucket: 'success-motors-98133.firebasestorage.app',
    measurementId: 'G-GY73F20XQ5',
  );
}
